// Code generated by "stringer -type=State -output=state_string.go -trimprefix=State"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateUnknown-0]
	_ = x[StateStart-1]
	_ = x[StateNewTrip-2]
	_ = x[StateNewTripName-3]
	_ = x[StateNewTripDate-4]
	_ = x[StateNewTripTime-5]
	_ = x[StateNewTripDescription-6]
	_ = x[StateNewTripConfirm-7]
	_ = x[stateSentinel-8]
}

const _State_name = "stateUnknownStartNewTripNewTripNameNewTripDateNewTripTimeNewTripDescriptionNewTripConfirmstateSentinel"

var _State_index = [...]uint8{0, 12, 17, 24, 35, 46, 57, 75, 89, 102}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
